name: CI-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

  build:
    runs-on: node-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: npm run build
